apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-spike
  annotations:
    backstage.io/techdocs-ref: dir:.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
