# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: backstage:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
#            - secretRef:
#                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
          readinessProbe:
            httpGet:
              port: 7007
              path: /.backstage/health/v1/readiness
          livenessProbe:
            httpGet:
              port: 7007
              path: /.backstage/health/v1/liveness
        - name: backstage-ui
          image: backstage-ui:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
